spring:
  application:
    name: zeus
  profiles:
    default: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 18080
  tomcat:
    accesslog:
      enabled: false
    mbeanregistry:
      enabled: true
    threads:
      max: 500

mybatis-plus:
  check-config-location: true
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

gitlab:
  host: https://gitlab.com
  access-token: xxx
  git-addr-prefix: git@gitlab.com

