spring:
  application:
    name: zeus
  profiles:
    default: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 18080
  tomcat:
    accesslog:
      enabled: false
    mbeanregistry:
      enabled: true
    threads:
      max: 500

mybatis-plus:
  check-config-location: true
  mapper-locations: classpath:/mapper/**.xml
