spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zeus?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&tinyInt1isBit=true
    username: root
    password: root

  data:
    redis:
      # 连接地址
      host: "127.0.0.1"
      # 端口
      port: 6379
      # 数据库
      database: 0
      # 用户名，如果有
      # username:
      # 密码，如果有
      # password:
      # 连接超时
      connect-timeout: 5s
      # 读超时
      timeout: 5s

zeus-task:
  base-url: http://127.0.0.1:19090
  task-url: ${zeus-task.base-url}/api/
  read-log-url: ${zeus-task.base-url}/api/readLog
