spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zeus?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&tinyInt1isBit=true
    username: root
    password: root