package com.wufeiqun.zeus.biz.cicd.entity;

import com.wufeiqun.zeus.dao.ApplicationDeployConfig;
import lombok.Data;
import lombok.ToString;


/**
 * 预处理, 把流程中需要的数据封装并且提前放到一个上下文环境中, 构建上下文, 可扩展
 */
@Data
@ToString
public class CicdBuildContext {
    /**
     * 前端入参form
     */
    private CicdBuildForm.RunBuildForm runBuildForm;
    /**
     * 创建者
     */
    private String operator;

    private ApplicationDeployConfig applicationDeployConfig;
    /**
     * 构建TAG, 用户选择分支, 然后基于用户选择的分支创建一个TAG来构建, 因为分值会变化, tag不会变化
     * 可以保留当时的上线数据原型
     */
    private String buildTag;
    /**
     * 用户选择分支以后使用会用选择的分支, 用户没有选择的时候使用默认的分支
     */
    private String buildBranch;
    private Long buildRecordId;
    private String autoGeneratedRunExtraArgs;

    public CicdBuildContext(CicdBuildForm.RunBuildForm runBuildForm, String operator) {
        this.runBuildForm = runBuildForm;
        this.operator = operator;
    }
}
